### PR TITLE
Some simplifications for the client class

### PR DESCRIPTION
**Pull request by Frigerius**
- changed query_available_abilities to allow batch requests
- added a simplified version of debug_text

### CODE REVIEW

**Comment by Frigerius** [comment]
added events for unit created/deleted and building construction completed

**Comment by BurnySc2** [comment]
I think there is a [small mistake here](https://github.com/Dentosal/python-sc2/pull/36/files#diff-602f2d30b3d1c40d82cd26d2df68b413R184) - the is bracket was at the wrong position and it should be:
```python
    async def query_available_abilities(self, units, ignore_resource_requirements=False):
        if not isinstance(units, list):
            assert isinstance(units, Unit)
            units = [units]
        assert len(units) > 0
        result = await self._execute(query=query_pb.RequestQuery(
            abilities=[query_pb.RequestQueryAvailableAbilities(
                unit_tag=unit.tag) for unit in units],
            ignore_resource_requirements=ignore_resource_requirements)
        )
        return [[AbilityId(a.ability_id) for a in b.abilities] for b in result.query.abilities]
```

**Comment by Frigerius** [comment]
will take a look

**Comment by BurnySc2** [comment]
Merged: b625c506ca25bc3371ffc60100237603933e0f68

**Pull request closed without merging**
