### PR TITLE
Add a visualizer for Linux via RGB rendering

### PR DESCRIPTION
**Pull request by islamelnabarawy**
This PR adds a functional visualizer that can be used on Linux systems to view the RGB observations while the game is in progress. This currently renders the map and minimap, and allows camera movement by left-clicking on the minimap similar to the Windows client.

To enable the visualizer, you need to add the following keyword argument to the `sc2.run_game()` call:

`rgb_render_config={'window_size': (1024, 768), 'minimap_size': (256, 256)}`

where you can specify the size of your main and minimap displays. 

**Note:** The recommended maximum window size is 720p (1280x720) due to limitations on the size of the protocol message. If you get the error `TypeError: Received message 258:WebSocketError('Message size 6496815 exceeds limit 4194304',) is not bytes`, try reducing your window size.

Please respond with any comments on what you think and any recommendations for improvements, as well as any additional features you think are needed.

Thanks!

EDIT: Re-created #137 after rebasing off develop branch.
EDIT: This is now ready to be considered for merging.

### CODE REVIEW

**Comment by islamelnabarawy** [comment]
For anyone trying to use this while it's still in development, if you start the game and nothing happens please check the log and go over the following checklist:
- The Command Line should have ` -eglpath libEGL.so` at the end of the line, if it doesn't then you're probably not loading the right version of python-sc2. Make sure you are using the right branch, either by merging this PR into your working copy or by checking out the [`rgb-rendering`](https://github.com/islamelnabarawy/python-sc2/tree/rgb-rendering) branch from [this fork](https://github.com/islamelnabarawy/python-sc2).
- Check the log messages directly after `Attempting to initialize EGL from file libEGL.so ...`, if it says it failed to find the library then you need to find the `libEGL.so` file on your system and add its path to the `LD_LIBRARY_PATH` environment variable in the same command shell that you run the code in.

As of this writing, the code doesn't open the rendering window until it gets the first RGB observation, and won't open it at all if the render interface doesn't get initialized correctly for any reason.

**Comment by islamelnabarawy** [comment]
I've refactored and organized the code some more, and added some useful information to the visualizer display. Here's a screenshot of what it looks like now:

visualizer

**Comment by MrRacoon** [comment]
Hey, I was looking to test this branch, and I was hoping you could lend some pointers on how to install this in my project instead of the current version. 
I've played around with `virtualenv` and `pipenv` and can't quite seem to get the incantation right.

I'm using:
`pipenv install -e git+https://github.com/islamelnabarawy/python-sc2@rgb-rendering#egg=sc2`

Am I hot or cold?

I'm really excited about this PR BTW. I just started getting into making bots for this game and seeing more features for linux is getting me pumped up!

**Comment by islamelnabarawy** [comment]
@MrRacoon That command looks like it would work. Have you tried running one of the examples with the `rgb_render_config` parameter? If not, try adding something like this at the end of the `sc2.run_game()` call in one of the files in the `examples` folder and see what happens:

`rgb_render_config={'window_size': (1280, 720), 'minimap_size': (256, 256)}`

For example, if you go into `examples/zerg/zerg_rush.py`, you would make the `main()` function look like this:

```
def main():
    sc2.run_game(
        sc2.maps.get("(2)CatalystLE"),
        [
            Bot(Race.Zerg, ZergRushBot()),
            Computer(Race.Terran, Difficulty.Medium)
        ],
        realtime=False,
        rgb_render_config={'window_size': (1280, 720), 'minimap_size': (256, 256)}
    )
```

If this doesn't work, please open an issue [on my fork here](https://github.com/islamelnabarawy/python-sc2/issues) to avoid adding too much noise to this PR.

**Comment by Dentosal** [comment]
Merged and pushed into master.

**Comment by islamelnabarawy** [comment]
@Dentosal It looks like the EGL library file you have in there isn't working right for what the game is expecting, and it's resulting in a failure in SC2's code itself:
```
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Successfully loaded EGL library!
eglQueryDevicesEXT Failed. EGL error 0x3000
```

I imagine you wouldn't be able to run the RGB layer of the game on there right now, even through DM's pysc2 or Blizzard's C++ example in the s2client-api repo. If you are in fact able to do that, please send me the log for comparison, maybe we can find a workaround.

Thanks for merging this PR!

**Pull request closed without merging**
